# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
site.baseurl: "https://edgahab.github.io" # the subpath of your site, e.g. /blog
site.url: "/BrowserPetWebsite/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

title: 桌宠系列：浏览器插件
email: fffeilian@gmail.com
description: "可可爱爱的桌宠"


# Team names, titles and social links
people:
- name: 黄飞廉
  pic: 1
  position: 产品经理，技术小组组长
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/feilian-huang-a6ba801a1/
    - title: github
      url: https://github.com/EDGAhab

- name: 吕虹云
  pic: 2
  position: EDG桌宠画师
  social:

- name: Kirin Pörsti
  pic: 3
  position: Asoul桌宠画师
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/kirin-p%C3%B6rsti-966b6617a/

- name: 肖遥
  pic: 4
  position: 开发者
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/yaoxiao56/
    - title: github
      url: https://github.com/yaoxiao6

- name: 沈诗瑶
  pic: 5
  position: 开发者
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/shiyao-shen/
    - title: github
      url: https://github.com/Shiyao-monster

- name: 崔航齐
  pic: 6
  position: 开发者
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/lucas-cui-701943213/
    - title: github
      url: https://github.com/Lucascuibu

- name: 甘皓元
  pic: 7
  position: 网页设计
  social:

- name: 敖敏欣
  pic: 8
  position: 网页设计
  social:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/EDGAhab

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty